### ISSUE TITLE
requirements.txt is incomplete

### ISSUE THREAD

**Issue by dietmar** [wonjune-kang/lvc-vc#6]
Nice work, thank you for sharing!

I couldn't get the code to run with the provided `requirements.txt` file.

- `torch>=1.13.1` and `torchaudio==0.13.0` is contradictory as far as I know
- `praat-parselmouth` and `transformers` are missing

I got it to work with this `requirements.txt` on Python 3.10.12:

```
librosa==0.9.2
matplotlib==3.5.2
numpy>=1.22
scipy>=1.10.0
torch>=1.13.1
torchaudio==0.13.1
tensorboard==2.10.0
tqdm==4.64.0
omegaconf==2.2.3
praat-parselmouth
transformers
```

You might want to specify concrete versions for the last two.
Cheers!

**Comment by wonjune-kang** [comment]
Thank you for pointing this out! I've updated ```requirements.txt``` to reflect your post and specified versions for ```praat-parselmouth``` and ```transformers```, hope it solves the issues.
